#!/usr/bin/env python3
"""Fix missing GN configuration files for ANGLE standalone build."""
import os

# Fix gclient_args.gni - normally generated by gclient
gclient_args = "/home/catarina/angle_build/angle/build/config/gclient_args.gni"
with open(gclient_args, 'w', newline='\n') as f:
    f.write('# Auto-generated for standalone ANGLE build\n')
    f.write('generate_location_tags = false\n')
    f.write('build_with_chromium = false\n')
print(f"Fixed {gclient_args}")

# Check if there's a rust toolchain VERSION file needed
rust_version = "/home/catarina/angle_build/angle/third_party/rust-toolchain/VERSION"
os.makedirs(os.path.dirname(rust_version), exist_ok=True)
if not os.path.exists(rust_version):
    with open(rust_version, 'w', newline='\n') as f:
        f.write('0\n')  # dummy since we disable rust
    print(f"Created dummy {rust_version}")

print("Done fixing config files")

